name: Cleanup after tests
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STREAM_API_KEY: ${{ vars.TEST_API_KEY }}
  STREAM_SECRET: ${{ secrets.TEST_SECRET }}

# Runs midnight at every Sunday https://crontab.guru/weekly
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Cleanup
        run: node test-cleanup.js
