name: Test
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STREAM_API_KEY: ${{ vars.TEST_API_KEY }}
  STREAM_SECRET: ${{ secrets.TEST_SECRET }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-node:
    strategy:
      matrix:
        version: [18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
  test-bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Bun@1
        uses: oven-sh/setup-bun@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Test
        run: bun run vitest
