name: Test
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STREAM_API_KEY: ${{ vars.TEST_API_KEY }}
  STREAM_SECRET: ${{ secrets.TEST_SECRET }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: [18, 20]
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
